# Node.js, Nginx, react application
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  branches:
    include:
      - main # Indentation is important here

pool:
  name: 'project-pool'  # Adjust as needed for your Azure Pipelines agent

stages:
- stage: Build
  jobs:
  - job: BuildImage
    displayName: Build image
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile' 
        tags: 'my-nginx:latest'

- stage: Deploy
  jobs:
  - job: DeployWithCompose
    displayName: Deploy using Docker Compose
    dependsOn: BuildImage
    steps:
    - task: DockerCompose@0
      displayName: Deploy with Docker Compose
      inputs:
        dockerComposeFile: '$(Build.SourcesDirectory)/docker-compose.yml' 
        action: 'Run a Docker Compose command'
        dockerComposeCommand: 'up -d'