# Node.js, Nginx, react application
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
 branches:
   include:
     - main # Indentation is important here

pool:
 name: 'project-pool' # Adjust as needed for your Azure Pipelines agent

stages:
- stage: Build
  jobs:
  - job: BuildImage
    displayName: "Build docker image"
    steps:
    - task: Docker@0
      displayName: "Build an docker image"
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile' 
        tags: 'my-nginx:latest'
    - task: Docker@0
      displayName: "Push a Docker image to container registry"
      inputs:
        azureSubscription:
        azureContainerRegistry:
        action: "push an image"
        imageName: "nginx:$(tag)"

