version: "3.9"
services:
  nginxservice:
    image: 'dockertestcontainer1.azurecr.io/dockertestimagenginx' 
    container_name: nginx
  deploy:
    replicas: 1
    restart_policy:
      condition: any
  ports:
    - "80:80"
